In [1]:
import pandas as pd
import folium
from folium.plugins import MarkerCluster

In [5]:
df = pd.read_csv('/content/Dataset .csv')

In [6]:
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [7]:
map_center = [df['Latitude'].mean(), df['Longitude'].mean()]
restaurant_map = folium.Map(location=map_center, zoom_start=12)

In [8]:
marker_cluster = MarkerCluster().add_to(restaurant_map)

for index, row in df.iterrows():
    folium.Marker([row['Latitude'], row['Longitude']],
                  popup=row['Restaurant Name']).add_to(marker_cluster)

In [9]:
restaurant_map.save('restaurant_distribution_map.html')

In [10]:
grouped_df = df.groupby('City')

In [13]:
concentration_map = folium.Map(location=map_center, zoom_start=12)

for city, city_df in grouped_df:
    city_marker = folium.Marker([city_df['Latitude'].mean(), city_df['Longitude'].mean()],
                                icon=folium.Icon(color='blue')).add_to(concentration_map)

In [14]:
concentration_map.save('restaurant_concentration_map.html')

In [15]:
average_ratings_by_city = grouped_df['Aggregate rating'].mean()

In [24]:
cuisines_by_city = grouped_df['Cuisines'].apply(lambda x: ',').reset_index()

In [26]:
price_ranges_by_city = grouped_df['Price range'].mean()

In [27]:
print("Average Ratings by City:")
print(average_ratings_by_city)

Average Ratings by City:
City
Abu Dhabi          4.300000
Agra               3.965000
Ahmedabad          4.161905
Albany             3.555000
Allahabad          3.395000
                     ...
Weirton            3.900000
Wellington City    4.250000
Winchester Bay     3.200000
Yorkton            3.300000
��stanbul          4.292857
Name: Aggregate rating, Length: 141, dtype: float64

In [28]:
print("Cuisines by City:")
print(cuisines_by_city)

Cuisines by City:
                City Cuisines
0          Abu Dhabi        ,
1               Agra        ,
2          Ahmedabad        ,
3             Albany        ,
4          Allahabad        ,
..               ...      ...
136          Weirton        ,
137  Wellington City        ,
138   Winchester Bay        ,
139          Yorkton        ,
140        ��stanbul        ,

[141 rows x 2 columns]

In [29]:
print("Price Ranges by City:")
print(price_ranges_by_city)

Price Ranges by City:
City
Abu Dhabi          3.300000
Agra               2.650000
Ahmedabad          2.571429
Albany             1.700000
Allahabad          2.650000
                     ...
Weirton            2.000000
Wellington City    3.250000
Winchester Bay     2.000000
Yorkton            2.000000
��stanbul          2.857143
Name: Price range, Length: 141, dtype: float64